[book]
authors = ["krizdano"]
language = "en"
multilingual = false
src = "src"
title = "Psychology"

[output.html]
additional-css = ["./theme/catppuccin.css"]
default-theme = "latte"
preferred-dark-theme = "mocha"
